-- MLB SQL BATTING REFERENCE

CREATE TABLE fifteen_batting (
TEAM TEXT PRIMARY KEY,
BATTINGAVG DECIMAL,
ONBASEPERCENT DECIMAL,
STOLENBASES INT,
HOMERUNS INT
);

CREATE TABLE fifteen_defense (
TEAM TEXT PRIMARY KEY,
SAVES INT,
RUNS INT,
HOMERUNS INT,
);

CREATE TABLE team_id (
Team TEXT PRIMARY KEY,
Tm TEXT,
);
